### ISSUE TITLE
Solved: RuntimeError: CUDA error: invalid device ordinal

### ISSUE THREAD

**Issue by Ajaingithub** [zhangyumeng1sjtu/EPACT#2]
Hi, 

Thanks for the amazing tool. I am planning to use it for my project. 

However while doing the test run I faced the error while running

`python scripts/pretrain/pretrain_plm.py --config configs/config-pretrain-epitope-lm.yml`

RuntimeError: CUDA error: invalid device ordinal
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

I have made some changes in the source file so if someone is facing same error can use this
In the source file /miniconda3/envs/EPACT_env2/lib/python3.10/site-packages/EPACT/trainer/plm_trainer.py 

Please make change in line def__init__(self,config) to

`class EpitopeLMTrainer(BaseTrainer):
    def __init__(self, config):
        super(EpitopeLMTrainer, self).__init__(config)
        
        if torch.cuda.is_available():
            self.device = torch.device("cuda:0")  
        else:
            self.device = torch.device("cpu")

        self.model = PeptideLM(**config.model)
        self.model.to(self.device)`

This will fix the above error. I hope this might be helpful.

**Comment by zhangyumeng1sjtu** [comment]
Thank you, Abhinav. Could you please provide the complete error log? Theoretically, the user only needs to set the "gpu_device" in the Config file.

**Comment by Ajaingithub** [comment]
Thank you Yumeng for the quick reply

This was the error log:

`Traceback (most recent call last):
  File "/diazlab/data3/.abhinav/tools/EPACT/scripts/pretrain/pretrain_plm.py", line 82, in <module>
    main(args)
  File "/diazlab/data3/.abhinav/tools/EPACT/scripts/pretrain/pretrain_plm.py", line 33, in main
    Trainer = EpitopeLMTrainer(config)
  File "/diazlab/data3/.abhinav/tools/miniconda3/envs/EPACT_env2/lib/python3.10/site-packages/EPACT/trainer/plm_trainer.py", line 20, in __init__
    self.model.to(self.device)
  File "/diazlab/data3/.abhinav/tools/miniconda3/envs/EPACT_env2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1343, in to
    return self._apply(convert)
  File "/diazlab/data3/.abhinav/tools/miniconda3/envs/EPACT_env2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 903, in _apply
    module._apply(fn)
  File "/diazlab/data3/.abhinav/tools/miniconda3/envs/EPACT_env2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 930, in _apply
    param_applied = fn(param)
  File "/diazlab/data3/.abhinav/tools/miniconda3/envs/EPACT_env2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1329, in convert
    return t.to(
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.`

Please let me know if you need any other information.

**Comment by Ajaingithub** [comment]
Thank you Yumeng for your reply

This was the error log

Traceback (most recent call last):
  File "./EPACT/scripts/pretrain/pretrain_plm.py", line 82, in <module>
    main(args)
  File "./EPACT/scripts/pretrain/pretrain_plm.py", line 33, in main
    Trainer = EpitopeLMTrainer(config)
  File "/miniconda3/envs/EPACT_env2/lib/python3.10/site-packages/EPACT/trainer/plm_trainer.py", line 20, in __init__
    self.model.to(self.device)
  File "/miniconda3/envs/EPACT_env2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1343, in to
    return self._apply(convert)
  File "/miniconda3/envs/EPACT_env2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 903, in _apply
    module._apply(fn)
  File "/miniconda3/envs/EPACT_env2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 930, in _apply
    param_applied = fn(param)
  File "/miniconda3/envs/EPACT_env2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1329, in convert
    return t.to(
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Please let me know if you need any other detail.

**Comment by zhangyumeng1sjtu** [comment]
I guess the error came from the default setting of the CUDA device number in `configs/config-pretrain-epitope-lm.yml`.

```yaml
training:
  gpu_device: 1
```

There may have been no second device on your machine. It may work after modifying the config file.

**Comment by Ajaingithub** [comment]
Yes thanks it worked changing the config file

```
training:
  gpu_device: 0
```
